basedosdados/pipelines

pipelines/bases/__init__.py, pipelines/bases/br_ibge_inpc/__init__.py, pipelines/bases/br_ibge_inpc/flows.py, pipelines/bases/br_ibge_inpc/schedules.py, pipelines/bases/br_ibge_inpc/tasks.py, pipelines/bases/br_ibge_ipca/__init__.py, pipelines/bases/br_ibge_ipca/flows.py, pipelines/bases/br_ibge_ipca/schedules.py, pipelines/bases/br_ibge_ipca/tasks.py, pipelines/bases/br_ibge_ipca15/__init__.py, pipelines/bases/br_ibge_ipca15/flows.py, pipelines/bases/br_ibge_ipca15/schedules.py, pipelines/bases/br_ibge_ipca15/tasks.py, pipelines/utils.py
**IMPORTANTE:** Esse PR já utiliza a versão atualizada do utils criada no #18 
Criei três datasets para os dados de índices de preços (IPCA, IPCA15, INPC). Testei as pipelines localmente, usando:
```python
from pipelines.utils import run_local
from functools import reduce
from pipelines.bases.br_ibge_ipca15 import (
br_ibge_ipca15_br,
br_ibge_ipca15_rm,
br_ibge_ipca15_municipio,
br_ibge_ipca15_geral,
)
from pipelines.bases.br_ibge_ipca import (
br_ibge_ipca_br,
br_ibge_ipca_rm,
br_ibge_ipca_municipio,
br_ibge_ipca_geral,
)
from pipelines.bases.br_ibge_inpc import (
br_ibge_inpc_br,
br_ibge_inpc_rm,
br_ibge_inpc_municipio,
br_ibge_inpc_geral,
)
flows_ipca = [br_ibge_ipca_br, br_ibge_ipca_rm, br_ibge_ipca_municipio, br_ibge_ipca_geral]
flows_ipca15 = [br_ibge_ipca15_br, br_ibge_ipca15_rm, …
```
=> [pipelines] adiciona dados de inflação

pipelines/utils/crawler_ibge_inflacao/tasks.py
O erro estava ocorrendo porque o nome dos arquivos na pasta temporária estava sendo alterado quando o prefect tentava rodar uma task novamente. Como consequência esse filtro não funcionava:
```python
arquivos = [
arquivo
for arquivo in glob.iglob("/tmp/data/input/mes/*")
if arquivo.split("/")[-1].split("_")[0] == indice
]
```
Incluí um código para apagar (se existir) a pasta temporária toda vez que o crawler começar novamente:
```python
os.system("[ -e /tmp/data/input/ ] && rm -r /tmp/data/input/")
os.system("[ -e /tmp/data/output/ ] && rm -r /tmp/data/output/")
```
=> [inflatio_data] fix file life-cycle inside temp folder

pipelines/utils/tasks.py
Os valores atuais de `location` e `dataset_is_public` em `tb.create` valem apenas para as pipelines da prefeitura. Em particular, usar uma localização do dataset do BQ diferente dos EUA para os datasets da BD gera um erro, uma vez que os buckets da BD estão nos EUA.
```python
tb.create(
path=header_path,
if_storage_data_exists="replace",
if_table_config_exists="replace",
if_table_exists="replace",
location="southamerica-east1",
dataset_is_public=dataset_is_public,
)
```
=> use default arguments in tb.create for location and dataset_is_public

pipelines/datasets/br_cgu_pessoal_executivo_federal/schedules.py
RRule Schedule não estava sendo reconhecido pelo Prefect, deixando os agendamentos de Runs errados. Troquei por CronClock baseado em testes na UI do Prefect:
PS: Dia 28 do próximo mês do dado, para ter mais chances do dataset ter sido atualizado na fonte.
=> [infra] [fix] Pipeline cgu pessoal executivo

pipelines/datasets/cross_update/flows.py, pipelines/datasets/cross_update/schedules.py, pipelines/datasets/cross_update/tasks.py
When the flow runs, it returns up to 100 pages (`page_size`), while looping over a range of all datasets (returned in `json_response['result']['count']`. Thus, it led to an error when there were more than 100 datasets in the complete result (from basedosdados api)
=> fixing cross_update

pipelines/datasets/br_rf_cafir/flows.py, pipelines/datasets/br_rf_cafir/utils.py
Corrige:
- nome da variável data_referencia na função extract_last_date
- Insere underlines '_' no parâmetro materialize_after_dump
=> [fix] br_rf_cafir

pipelines/datasets/br_inmet_bdmep/flows.py, pipelines/datasets/br_inmet_bdmep/schedules.py, pipelines/datasets/br_inmet_bdmep/tasks.py
=> [fix] fixing `br_inmet_bdmep` 

pipelines/datasets/br_ms_cnes/tasks.py
- Corrige erro na task `check_files_to_parse`; meses maiores que 9 eram passados como int na hora de criar a string `year_month_to_parse`, qubrando o flow. 
```py
year = str(last_date.year)
month = last_date.month
if month <= 11:
month = month + 1
else:
month = 1
year = year[2:4]
if month <= 9:
month = "0" + str(month)
else:
month = str(month)
year_month_to_parse = year + month) 
```
=> [fix] br_ms_cnes

pipelines/datasets/br_mp_pep_cargos_funcoes/tasks.py
`datetime.date` e `datetime.datetime` não são iguais para os mesmo parâmetros (ano, mês e dia).
`get_api_most_recent_date` retorna uma classe `datetime.date` mas eu estava comparando com `datetime.datetime`
=> fix: br_mp_pep.cargos_funcoes

pipelines/datasets/br_ibge_ipca15/schedules.py
- A definição da schedule e o import dela no flow estão corretos. Por algum motivo, a nova schedule (run diária) não substitui a antiga schedule (runs mensais);
=> [fix] br_ibge_ipca15.mes_brasil

pipelines/datasets/br_cgu_beneficios_cidadao/tasks.py, pipelines/datasets/br_cgu_beneficios_cidadao/utils.py, pipelines/datasets/mundo_transfermarkt_competicoes/flows.py, pipelines/datasets/mundo_transfermarkt_competicoes/tasks.py, pipelines/datasets/mundo_transfermarkt_competicoes/utils.py, pipelines/utils/metadata/tasks.py
close #753
- Dentro da função `execucao_coleta` a lista de times visitantes e mandantes estava com um tamanho maior do que a quantidade total de partidas do campeonato.
**v1.0**
- Corrige o tamanho da lista dos times/partidas
- Adiciona task que retorna a data do último jogo e verifica se há a necessidade de atualização
- Corrige a lista de times, removendo os jogos que estão com a `class="matchresult rescheduled"`, agora o crawler só itera pelos jogos que já aconteceram. Antes iterava por todos os jogos da temporada
- Corrige lógica para pegar o nome dos técnicos
- Também adiciona retry em uma task no flow `br_cgu_beneficios_cidadao`
**v1.1**
- Corrige idade média dos jogadores e valor do clube mandante e visitante
=> [fix]: `br_transfermarkt_competicoes.brasileirao_serie_a`

pipelines/datasets/br_anp_precos_combustiveis/utils.py
- Apenas acrescentei o `verify = False` para nao verificar o SSL.
=> [fix] br_anp_precos_combustiveis

pipelines/constants.py, pipelines/utils/execute_dbt_model/constants.py, pipelines/utils/execute_dbt_model/tasks.py
- Modifica parâmetro que define quantidades de novas tentativas após quebra da task run_dbt_model
=> run_dbt_model

pipelines/datasets/br_b3_cotacoes/flows.py
* Pipeline sendo desativada porque não está mais disponível no front-end devido a [regulamentação legais](https://discord.com/channels/787841210433536010/1150466644934676540/1176520645073457292) e também é bem custosa para rodar diariamente, segue a [discussão](https://discord.com/channels/787841210433536010/970815278755766413/1278338607962259546).
=> [Deactivate] br_b3_cotacoes

pipelines/datasets/br_me_cnpj/utils.py
**Problema:**
- O atributo HTML que estava sendo raspado estava errado. No lugar de raspar a data relativa a última atualização do conjunto br_me_cnpj, estava raspando a data inicial de disponibilização do conjunto pela Receita Federal.
**Solução:**
- Alterei a função data_url, utlizada pela task get_data_source_max_date, para extrair a data mais recente. Apenas modifiquei o índice que indicava qual data extrair.
=> [fix] br_me_cnpj

pipelines/datasets/br_ibge_inpc/flows.py, pipelines/datasets/br_ibge_inpc/schedules.py, pipelines/datasets/br_ibge_ipca/flows.py, pipelines/datasets/br_ibge_ipca15/flows.py, pipelines/utils/crawler_ibge_inflacao/flows.py
Neste PR
1. Corrigo typo na schedule de ibge_inpc.mes_categoria_municipio;
2. Atualizo os code_owners
=> [fix] br_ibge_

.github/workflows/build-docker.yaml, .github/workflows/cd-staging.yaml, .github/workflows/cd.yaml, .github/workflows/ci-docker.yaml, .github/workflows/ci-python.yaml, .github/workflows/ci.yaml, .github/workflows/docs.yaml
Recentemente houve uma atualização na [ultima versão do Ubuntu 24.04.1][ubuntu-patch] disponível para gerar os containers dos nossos Actions.
Porém, com a versão nova o [python padrão vem com a versão 3.12][python-change]. O que causa [incompatibilidade com nosso repositório][poetry-lock] e também a versão mais recente do [ultima versão do Ubuntu 24.04.1][ubuntu-patch] está dando erro em um pacote referente ao [R][r].
- Erro python-version: [Log completo][exemplo-erro-python]
> Run poetry install --only=test
The currently activated Python version 3.12.3 is not supported by the project (>=3.10,<3.11).
Trying to find and use a compatible version. 
Poetry was unable to find a compatible version. If you have one, you can explicitly use it via the "env use" command.
Error: Process completed …
=> [fix].github/workflows

pipelines/datasets/br_cvm_fi/tasks.py
- Explique de maneira clara e concisa o objetivo deste PR. O que foi alterado? Qual o problema que ele resolve?
Este PR lida com a mudança de nome da variável CNPJ_FUNDO para CNPJ_FUNDO_CLASSE em algumas divulgações mensais da tabela documentos_informe_diario
- Adicionar CNPJ_FUNDO_CLASSE como coluna a ser renomeada, caso exista
=> [Bugfix] br_cvm_fii

pipelines/datasets/br_me_cnpj/constants.py, pipelines/datasets/br_me_cnpj/flows.py, pipelines/datasets/br_me_cnpj/tasks.py, pipelines/datasets/br_me_cnpj/utils.py
Este PR refatora a função data_url responsável por extrair a data mais recente de atualização dos dados 
- Altera a função data_url que faz o parsing da data mais recente de divugalção dos dados no endpoint da Receita Federal. 
- Retira a chamada da função da data_url dentro da task main e insere um novo parâmetro na função main para aproveitar o resultado da primeira chamada a API que extrai a data mais recente;
- Insere novos parâmetros em todas as chamadas da task main no flow
**Caso haja algo relacionado aos testes que vale a pena informar:**
=> [Refactor] br_me_cnpj

pipelines/datasets/br_cvm_fi/tasks.py
- Este PR dropa colunas da fonte original que são inteiramente nulas e não presentes na tabela final documentos_informe_diario
- Este flow usa as colunas mapeadas na tabela de arquitetura para renomear  as variáveis. Como as colunas CNPJ_FUNDO e TP_FUNDO mudaram para, CNPJ_FUNDO_CLASSE e TP_FUNDO_CLASSE, apliquei estas mudanças na tabela de arquitetura
- Atualizei os últimos 12 meses de dados no Storage de dev com a [run](https://prefect.basedosdados.org/default/flow-run/cefd3b57-3009-44da-aa7f-0613a2a20875)
- Testei os dados em Dev
- Levei os dados para produção com o flow transfer_files_to_production [run](https://prefect.basedosdados.org/default/flow-run/e9b471ac-09b9-4130-a6e5-56daa6170dfb)  
- Materializei a tabela com o [flow](https://prefect.basedosdados.org/default/flow-run/850d9a3 …
=> [Refactor] br_cvm_fi

pipelines/utils/crawler_anatel/banda_larga_fixa/flows.py, pipelines/utils/crawler_anatel/banda_larga_fixa/tasks.py, pipelines/utils/crawler_anatel/banda_larga_fixa/utils.py, pipelines/utils/crawler_anatel/telefonia_movel/flows.py, pipelines/utils/crawler_anatel/telefonia_movel/tasks.py, pipelines/utils/crawler_anatel/telefonia_movel/utils.py
- Explique de maneira clara e concisa o objetivo deste PR. O que foi alterado? Qual o problema que ele resolve?
- Refatorando a pipeline para tornar o ano e semestre valores próprios e não precisar alterar manualmente.
=> [refactor] br_anatel

pipelines/datasets/br_cvm_fi/tasks.py
Este PR faz o re deploy da pipeline br_cvm_fi que falhou no [anterior](https://github.com/basedosdados/pipelines/actions/runs/11729598296)
=> [BugFix] br_cvm_fi

pipelines/datasets/br_rf_cno/constants.py, pipelines/datasets/br_rf_cno/tasks.py
- Este PR muda os endpoints de extração dos dados e refatora o crawler
- O crawler busca pelo nome no arquivo, cno.zip, e extrai a última data de atualização para decidir se deve ser atualizado ou não. Caso o nome do arquivo mude, será triggado um Value Error.
=> [BugFix] br_rf_cno

pipelines/datasets/br_ms_sinan/flows.py, pipelines/datasets/br_ms_sinan/schedules.py, pipelines/utils/crawler_datasus/flows.py, pipelines/utils/crawler_datasus/tasks.py, pipelines/utils/crawler_datasus/utils.py
- Já tinha subido as alterações, mas apesar de ter testado em dev, em produção continua dando erro. Registrando novamente para verificar se conserta prod.
=> [Data] br_ms_sinan.microdados_dengue

pipelines/utils/crawler_cgu/flows.py, pipelines/utils/crawler_cgu/tasks.py, pipelines/utils/crawler_cgu/utils.py
- Consertando a pipeline de CGU - Cartão de pagamento. Foi um erro que a pipeline não entrava em uma condição.
=> [BugFix] br_cgu_cartao_pagamento

pipelines/utils/crawler_anatel/banda_larga_fixa/flows.py, pipelines/utils/crawler_anatel/banda_larga_fixa/utils.py, pipelines/utils/crawler_anatel/telefonia_movel/flows.py, pipelines/utils/crawler_anatel/telefonia_movel/utils.py
- Consertando a pipeline da anatel, quebrava por erro do time-out.
- O aumento do tempo não altera em nada na pipeline, uma vez que a função `WebDriverWait` acontece apenas quando o elemento estiver disponível.
=> [Bugfix] br_anatel

pipelines/datasets/br_rf_cafir/constants.py, pipelines/datasets/br_rf_cafir/flows.py, pipelines/datasets/br_rf_cafir/tasks.py, pipelines/datasets/br_rf_cafir/utils.py, pipelines/datasets/br_rf_cno/flows.py, pipelines/datasets/br_rf_cno/tasks.py, pipelines/datasets/br_rf_cno/utils.py
- Este PR modifica headers, insere time outs e modifica lógica de retry das requisições feitas ao  FTP da receita federal 
- Modifica o endpoint da pipeline imoveis_rurais do br_rf_cafir
=> [Refactor] br_rf_cno & br_rf_cafir

pipelines/datasets/br_me_cnpj/flows.py, pipelines/datasets/br_me_cnpj/utils.py
- Este PR reativa a schedule do conjunto br_me_cnpj
=> [Reactivate] br_me_cnpj

pipelines/datasets/br_stf_corte_aberta/utils.py
- Houve uma alteração no `xpath` do botão de download.
=> [fix] br_stf_corte_aberta

CONTRIBUTING.md, README.md
Depois da atualização no site da BD para suporta múltiplos idiomas nossa imagem de logo da BD fico com o link quebrado.
PR altera o caminho da imagem para do logo que se encontra em [docs][docs]
[docs]: https://github.com/basedosdados/sdk/blob/master/docs/docs/pt/images/bd_minilogo.png
=> [Fix]Concertar imagem bd_minilogo

pipelines/datasets/br_inmet_bdmep/flows.py
- Este flow tem uma configuração dinâmica no schedule. O parâmetro ano, utilizado para compor a URL de download do arquivo, é gerado com o ano corrente. Já estamos em 2025 e o dado na fonte original ainda está em 2024. Logo, a requisição toma 404
. Desativar a pipeline por enquanto e reativa quando a nova atualização sair na [fonte original](https://portal.inmet.gov.br/dadoshistoricos/)
=> [Deactivate] br_inmet_bdmep

pipelines/datasets/br_cvm_fi/tasks.py
- Altera nome da coluna CNPJ_FUNDO para CNPJ_FUNDO_CLASSE, em função da mudança na fonte original
=> [BugFix]: br_cvm_fii.documentos_perfil_mensal

pipelines/utils/metadata/utils.py
Depois de #931 apareceu alguns erros devido a alterações nas respostas do backend.
[Log de erro de br_ibge_ipca15.mes_categoria_municipio](https://prefect.basedosdados.org/default/flow-run/2231ae5f-4268-49e2-9536-273aaf9810f1?logs)
```
Task 'check_for_updates': Exception encountered during task execution!
Traceback (most recent call last):
File "/opt/venv/lib/python3.10/site-packages/prefect/engine/task_runner.py", line 876, in get_task_run_state
value = prefect.utilities.executors.run_task_with_timeout(
File "/opt/venv/lib/python3.10/site-packages/prefect/utilities/executors.py", line 454, in run_task_with_timeout
return task.run(*args, **kwargs)  # type: ignore
File "/home/runner/work/pipelines/pipelines/pipelines/utils/crawler_ibge_inflacao/tasks.py", line 131, in check_for_updates …
```
=> fix parse_datetime_ranges

pipelines/datasets/mundo_transfermarkt_competicoes/flows.py
Schedule `mundo_transfermarkt_competicoes.copa_brasil` será desativado pela descontinuidade da pipeline. Possível mudanças para pipeline com sofascore como responsável dos dados.
=> [Deactivate]  Desativando schedule mundo_transfermarkt_competicoes.copa_brasil

.github/workflows/cd-staging.yaml, .github/workflows/cd.yaml, .github/workflows/triggers-elementary-model.yaml
A action setup-python pode fazer o setup do python lendo o arquivo `.python-version` que já é usado pelo pyenv.
[skip ci]
=> [chore]: action setup-python read `.python-version`

.github/workflows/cd.yaml
Esse step leva ~5min/6min para deletar flows arquivados. Se alguém for mesclar um PR com o table-approve tem que esperar esse step. Até mesmo para quem mexe em pipelines para ser desnecessário no momento.
Acho que podemos fazer em um job separado, mas é melhor investigar como é processo de deletar flows arquivados. Atualmente ele parece deletar os mesmos flow toda vez que roda.
=> [chore]: deploy-production remove step delete archieved flow runs

models/br_camara_dados_abertos/schema.yml
- O teste da pipeline está quebrando devido a coluna `url_anterior` ter se reduzido a proporção de nulos para menor que 1%. Dessa forma, estou consertando a `not_null_proportion_multiple_columns`. 
- Alterei o combination_of_columns para ano, acredito que combine mais e esteja mais certo do que data_hora_ultimo_status
=> [BugFix] br_camara_dados_abertos.proposicao_microdados

.github/workflows/cd.yaml, .github/workflows/scripts/register_flows.py
O comportamento atual é registrar todos os flows em prod quando um PR é mesclado, isso leva ~6min. Se o PR mesclado for apenas um modificação em um .sql para rodar o table-approve tem que esperar todos os registros dos flows.
Em staging só registramos os flows que foram alterados ou afetado por uma alteração.
Em `cd-staging` é usado o parâmetro `--filter-affected-flows`.
Não sei porque em prod é forçado o registro de todos os flows, parece uma medida de segurança, mas não parece ser necessário, só em alguns casos.
Nesse PR adiciono `--filter-affected-flows` para registrar apenas os flows afetados. No entanto, se `pyproject.toml` ou `poetry.lock` for modificado todos os flows serão registrados porque pode existir uma atualização de dependência que não sabemos qual flows será afetado.
Obs: …
=> [chore]: deploy-production register only modified flows

CONTRIBUTING.md
Antes de instalar o R precisamos sincronizar usando `sudo apt-get update`. Peguei esse erro testando o GitHub Codespaces.
```
- Installing rpy2 (3.5.17): Failed
ChefBuildError
Backend subprocess exited when trying to invoke get_requires_for_build_wheel
Unable to determine R home: [Errno 2] No such file or directory: 'R'
cffi mode is CFFI_MODE.ANY
Looking for R home with: R RHOME
Unable to determine R home: [Errno 2] No such file or directory: 'R'
R home found: None
Error: rpy2 in API mode cannot be built without R in the PATH or R_HOME defined. Correct this or force ABI mode-only by defining the environment variable RPY2_CFFI_MODE=ABI
at ~/.local/share/pypoetry/venv/lib/python3.12/site-packages/poetry/installation/chef.py:164 in _prepare
160│ 
161│                 error = …
```
=> [docs]: update before install r-base

.github/workflows/scripts/prefect_run_dbt.py
Bug adicionado em #1106.
```
Traceback (most recent call last):
File "/home/runner/work/pipelines/pipelines/.github/workflows/scripts/prefect_run_dbt.py", line 443, in <module>
else get_datasets_and_tables_for_modified_files(
File "/home/runner/work/pipelines/pipelines/.github/workflows/scripts/prefect_run_dbt.py", line 336, in get_datasets_and_tables_for_modified_files
modified_files_list = modified_files.split(",")
AttributeError: 'list' object has no attribute 'split'
```
=> [bugfix]: AttributeError: 'list' object has no attribute 'split'

.github/workflows/scripts/register_flows.py
Em #1103 @tricktx reportou que o flow não registrou.
Ele adicinou um novo flow com arquivos do DBT. O problema é que `source_to_flows[key] = eval_execute_dbt_model` sobrescrever o valor na chave do dicionario. Na verdade devemos usar `.extend` para adicionar um flow na lista.
=> [bugfix]: register flows

CONTRIBUTING.md
Durante o processo de subida dos dados em #1112 o @galvd teve problema para instalar o `rpy2`. Teve que instalar algumas bibliotecas a mais.
Esse PR adicionar essas bibliotecas extras no guia de contribuição
=> [docs]: update `rpy2` install

CONTRIBUTING.md, poetry.lock, pyproject.toml
O grupo test tem duas dependências: networkx e parameterized. networkx já está no grupo dev e parameterized já uma dependência de pipelines.
Parte de #1008.
=> [chore]: remove group test from `pyproject.toml`

.github/workflows/scripts/code_tree_analysis.py, .github/workflows/scripts/register_flows.py
Esse PR alterar o comportamento de registro de flows.
- Se uma alteração foi feita em um `flows.py` o flow não é registrado, foi o que aconteceu em #1124 e em #1088
O principal motivo era que script `code_tree_analysis.py` faz a análise apenas das referências onde aquele arquivo era utilizado.
Exemplo: Se a alteração for em `pipelines/datasets/br_bd_siga_o_dinheiro/flows.py`
```sh
poetry run python .github/workflows/scripts/code_tree_analysis.py "pipelines/datasets/br_bd_siga_o_dinheiro/flows.py" --write-to-file
```
```sh
cat dependent_files.txt
```
```
pipelines/datasets/__init__.py
```
Se a alteração fosse em `pipelines/datasets/br_bd_siga_o_dinheiro/tasks.py`:
```sh
poetry run python .github/workflows/scripts/code_tree_analysis.py "pipelines/datasets/br_bd_siga_o_dinheiro/tasks.py" …
```
=> [chore]: Fix register flows

pipelines/datasets/br_me_comex_stat/tasks.py
Este PR retira validação de certificados SSL em função da ausência dele no domínio 
Ex. [erro](https://prefect.basedosdados.org/default/flow-run/00f846cf-ae57-413b-99ea-fd23c14cbb19?logs)
=> [Bugfix] br_me_comex_stat

.github/workflows/cd-staging.yaml, .github/workflows/triggers-elementary-model.yaml
`uv` instala `rpy2` mesmo quando quero instalar apenas as dependências de desenvolvimento `uv sync --locked --only-dev`.
Como `rpy2` não está disponível no runner mais recente isso gera um erro.
=> [chore]: switch to ubuntu-22.04

models/br_ms_cnes/br_ms_cnes__profissional.sql
Substituição do uso de `substr` e `cast` para obter os valores de `ano` e `mes` a partir da coluna `competen`, para uma abordagem mais direta utilizando `safe_cast` nos campos `ano` e `mes`.
*`competen` nas ultimas extrações tiveram casos dele vim como `000000` impossibilitando a extração do ano e mes usando o   `substr`*
Teste:
```sql
with tabela_validar as (SELECT 
ano, 
mes,
safe_cast(ano as int64) as ano_int,
safe_cast(mes as int64) as mes_int,
cast(substr(competen, 1, 4) as int64) as ano_competen,
cast(substr(competen, 5, 2) as int64) as mes_competen, 
competen,
FROM `basedosdados-dev.br_ms_cnes_staging.profissional`
where ano = "2020")
select * from tabela_validar
where ano_int != ano_competen and mes_int != mes_competen
```
Usando código a cima foi testando em diversos anos que a …
=> [fix] br_ms_cnes__profissional, ano e mes

dbt_project.yml
O principal motivo é que ao executar um pipeline a função `dump_header_to_csv` usada em `create_table_and_upload_to_gcs` salva arquivos no diretório `data` e o `dbt` reporta o seguinte erro.
`dump_header_to_csv`:
https://github.com/basedosdados/pipelines/blob/700f35d36c2382f08ee7e4c2094d432f53c785ea/pipelines/utils/utils.py#L605
```
$ dbt run --select models/test_dataset/test_dataset__test_table.sql
/home/pedro/Desktop/bd/pipelines/.venv/lib/python3.10/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.20) or chardet (5.2.0)/charset_normalizer (2.0.9) doesn't match a supported version!
warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
01:12:00  Running with dbt=1.5.6
01:12:01  Registered adapter: bigquery=1.5.9 …
```
=> [bugfix]: remove `seed-paths` from dbt
