- pipelines/bases/br_cvm_administradores_carteira/schedules.py
- pipelines/bases/br_cvm_oferta_publica_distribuicao/schedules.py
- pipelines/bases/test_pipeline/schedules.py
- pipelines/constants.py
- pipelines/{{cookiecutter.project_name}}/schedules.py
- Adiciona label para o Agent de prod
- Conserta o label para o Agent dev
> [Fix] Agent labels

- pipelines/datasets/__init__.py
- pipelines/datasets/br_cvm_administradores_carteira/flows.py
- pipelines/datasets/br_ibge_inpc/flows.py
- pipelines/datasets/br_ibge_ipca/flows.py
- pipelines/datasets/br_ibge_ipca15/flows.py
- pipelines/utils/tasks.py
- test_local.py
Esse PR adiciona o argumento `upstream_tasks` para os flows existentes.
> [fix] Add upstream tasks to flows

- pipelines/datasets/br_cvm_administradores_carteira/flows.py
- pipelines/datasets/br_cvm_oferta_publica_distribuicao/flows.py
- pipelines/utils/crawler_ibge_inflacao/flows.py
- pipelines/utils/tasks.py
- pipelines/utils/utils.py
Descrição
Agora as etapas `dump_header_to_csv`, `create_bd_table` e `upload_to_gcs` acontecem em uma única task `create_table_and_upload_to_gcs`
> [infra] create table upload gcs in one task

- pipelines/utils/tasks.py
Criei uma task que pode ser usada quando o usuário quiser editar o tipo das variáveis que serão tipadas na VIEW criada pelo `publish.sql`. Em parte, usei uma função que existe no pacote em python da bd, mas incluí a possibilidade de edição. Penso que essa task pode ser útil para quando a base for nova e/ou não tiver um `yaml` maduro ainda.
> add update_publish_sql task

- pipelines/datasets/br_cgu_pessoal_executivo_federal/tasks.py
- Resultado antes da modificação:
- Resultado depois da modificação:
> [infra] [fix] Pipeline `cgu pessoal executivo`

- pipelines/datasets/br_bd_indicadores/flows.py
- pipelines/datasets/br_bd_indicadores/tasks.py
- pipelines/datasets/br_bd_indicadores/utils.py
- pipelines/datasets/br_tse_eleicoes/flows.py
- pipelines/datasets/br_tse_eleicoes/tasks.py
- pipelines/datasets/br_tse_eleicoes/utils.py
- poetry.lock
- pyproject.toml
Essa é a primeira tabela de analytics que servirá de base para uma API a ser consumida pela equipe de FrontEnd.
As dimensões e métricas foram selecionadas da seguinte lista: https://developers.google.com/analytics/devguides/reporting/data/v1/realtime-api-schema
> [infra] add Real Time analytics data

- pipelines/datasets/br_fgv_igp/flows.py
- pipelines/datasets/br_fgv_igp/schedules.py
- pipelines/datasets/br_fgv_igp/tasks.py
- pipelines/datasets/br_fgv_igp/utils.py
Novo PR, com os fluxos de 7 índices do IGP/FGV disponíveis no Ipeadata
> [feat] fgv igp

- .github/workflows/build-docker.yaml
- .github/workflows/cd_staging.yaml
- .github/workflows/scripts/code_tree_analysis.py
- .github/workflows/scripts/register_flows.py
- pipelines/datasets/br_fgv_igp/utils.py
- pipelines/datasets/br_me_comex_stat/tasks.py
- pipelines/datasets/br_me_comex_stat/utils.py
- requirements-deploy.txt
- Script de registrar flows permite registrar com schedule habilitado ou desabilitado
- Adiciona action para registrar flows em staging (e com schedule desabilitado) em pull requests partindo de branches com prefixo `staging/` (exemplo: `staging/minha-nova-feature`)
- Paralelização da construção do container de pipelines para agilizar o registro na API do Prefect
> [FEAT] Adiciona ambiente de staging

- pipelines/datasets/br_tse_eleicoes/tasks.py
- pipelines/utils/crawler_ibge_inflacao/tasks.py
- pipelines/utils/crawler_ibge_inflacao/utils.py
Tabelas de região metropolitana não estavam baixando e gerando o erro ` requests.exceptions.SSLError: HTTPSConnectionPool(host='xxxxx', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, u'[SSL: VERSION_TOO_LOW] version too low (_ssl.c:726)'),))`
Adicionei uma classe no utils para lidar com esse caso.
> [infra] fix SSL issue inflation (tabelas regiao metropolitana)

- pipelines/datasets/br_bd_indicadores/flows.py
- pipelines/datasets/br_bd_indicadores/schedules.py
- pipelines/datasets/br_bd_indicadores/tasks.py
- pipelines/datasets/br_bd_indicadores/utils.py
- pipelines/utils/constants.py
Inclusão da tabela (via Google Sheets) em pipeline
Issue #245
> [infra] add BD Contabilidade to pipeline

- pipelines/datasets/br_bd_indicadores/flows.py
- pipelines/datasets/br_bd_indicadores/tasks.py
Adding a parameter to limit the number of columns used, as in pessoas blank columns were being read
> [fix] adding usecols to prevent empty lines to be read

- pipelines/datasets/br_bd_indicadores/flows.py
- pipelines/datasets/br_bd_indicadores/tasks.py
- pipelines/utils/utils.py
Treat thousands separations in contabilidade table
> [fix] correcting floats in pt-br format

- pipelines/constants.py
Add team dados code owners to pipelines/constants.py file
> add team dados code owners to constants.py file

- pipelines/datasets/br_me_comex_stat/constants.py
- pipelines/datasets/br_me_comex_stat/flows.py
- pipelines/datasets/br_me_comex_stat/schedules.py
- pipelines/datasets/br_me_comex_stat/tasks.py
- pipelines/datasets/br_me_comex_stat/utils.py
- register flows of `br_me_comex_stat` for testing purposes
> [test] br_me_comex_stat

- pipelines/datasets/br_bcb_agencia/flows.py
- pipelines/datasets/br_bcb_estban/flows.py
- pipelines/datasets/br_cgu_pessoal_executivo_federal/flows.py
- pipelines/datasets/br_cvm_administradores_carteira/flows.py
- pipelines/datasets/br_cvm_oferta_publica_distribuicao/flows.py
- pipelines/datasets/br_fgv_igp/flows.py
- pipelines/datasets/br_ibge_pnadc/flows.py
- pipelines/datasets/br_inmet_bdmep/flows.py
- pipelines/datasets/br_jota/flows.py
- pipelines/datasets/br_me_comex_stat/flows.py
- pipelines/datasets/br_ons_estimativa_custos/flows.py
- pipelines/datasets/br_poder360_pesquisas/flows.py
- pipelines/datasets/br_sp_saopaulo_dieese_icv/flows.py
- pipelines/datasets/br_tse_eleicoes/flows.py
- fix default materialization mode to `prod`
> [fix] Default materialization mode

- pipelines/datasets/__init__.py
- pipelines/datasets/br_me_comex_stat/flows.py
- pipelines/datasets/br_me_comex_stat/schedules.py
- pipelines/datasets/br_me_comex_stat/tasks.py
- pipelines/datasets/br_me_comex_stat/utils.py
> br_me_comex_stat

- .github/workflows/productivity.yml
Action to schedule the creation of productivity issues for the pipelines team, create a new one every Monday morning.
Source: https://docs.github.com/en/actions/managing-issues-and-pull-requests/scheduling-issue-creation
> Create `productivity.yml` action

- pipelines/datasets/br_anp_precos_combustiveis/schedules.py
- pipelines/utils/utils.py
Na função to_partitions, define 'csv' como valor default do parâmetro file_type para não precisar modificar flows antigos que usam csv.
> fix to_partitions

- pipelines/datasets/br_mp_pep_cargos_funcoes/flows.py
- pipelines/datasets/br_mp_pep_cargos_funcoes/tasks.py
A pipeline rodou e os dados foram atualizados em prod para o mês 7. Alterei os parâmetros para `prod`.
> [fix] br_mp_pep_cargos_funcoes

- pipelines/datasets/br_bcb_agencia/flows.py
- pipelines/datasets/br_bcb_agencia/schedules.py
- pipelines/datasets/br_bcb_estban/flows.py
- pipelines/datasets/br_bcb_estban/schedules.py
- Conserta parâmetros na schedule da br_bcb_agencia e br_bcb_estban
> fix br_bcb_estban | br_bcb_agencia

- pipelines/datasets/br_ms_cnes/flows.py
- pipelines/datasets/br_ms_cnes/schedules.py
- pipelines/utils/metadata/tasks.py
> [fix] br_ms_cnes

- pipelines/datasets/br_cvm_fi/constants.py
- pipelines/datasets/br_cvm_fi/flows.py
- pipelines/datasets/br_cvm_fi/tasks.py
> [fix] br_cvm_fi

- pipelines/datasets/br_ms_cnes/flows.py
corrige input de 2 tasks do flow estabelecimento_filantropico
> [fix] `br_ms_cnes.estabelecimento_filantropico`

- pipelines/datasets/br_cvm_administradores_carteira/flows.py
- pipelines/datasets/br_cvm_administradores_carteira/schedules.py
- pipelines/datasets/br_cvm_oferta_publica_distribuicao/flows.py
- pipelines/datasets/br_cvm_oferta_publica_distribuicao/schedules.py
- corrige erro de preenchimento nas schedules e no nome da equipe
1. br_cvm_administradores_carteira
2. br_cvm_oferta_publica_distribuicao
> [fix] br_cvm

- pipelines/datasets/br_me_comex_stat/flows.py
- pipelines/datasets/br_me_comex_stat/schedules.py
- pipelines/datasets/br_stf_corte_aberta/flows.py
minor fixes
* include update_metadata parameter
* fix delta in update_metadata
* change schedules so it runs tomorrow
> [fix] br_me_comex

- pipelines/datasets/br_ibge_inpc/schedules.py
- pipelines/datasets/br_ibge_ipca/schedules.py
- pipelines/datasets/br_ibge_ipca15/schedules.py
- pipelines/utils/crawler_ibge_inflacao/flows.py
- pipelines/utils/crawler_ibge_inflacao/tasks.py
-conserta parâmetros nas schedules e na task check for updates
> [fix] br_ibge_

- pipelines/datasets/br_stf_corte_aberta/flows.py
- pipelines/datasets/br_stf_corte_aberta/tasks.py
- pipelines/datasets/br_stf_corte_aberta/utils.py
> [fix] br_stf_corte_aberta

- pipelines/utils/utils.py
Não cheguei a testar localmente, implementei primariamente pela documentação
> fix: ignore prefect msg hook for staging

- pipelines/utils/execute_dbt_model/flows.py
- pipelines/utils/execute_dbt_model/tasks.py
- pipelines/utils/metadata/tasks.py
- pipelines/utils/metadata/utils.py
* inclui a possibilidade de adicionar flags no flow de run_dbt_model
* inclui a possibilidade de adicionar vars no flow de run_dbt_model
* permite rodar todos os modelos de um conjunto de uma vez
* faz um log com o comando que está sendo rodado
> [feat] new vars to run_dbt_model

- pipelines/datasets/br_cvm_oferta_publica_distribuicao/flows.py
- pipelines/datasets/br_cvm_oferta_publica_distribuicao/schedules.py
- pipelines/datasets/br_cvm_oferta_publica_distribuicao/tasks.py
- pipelines/utils/metadata/flows.py
> fix: br_cvm_oferta_distribuicao_publica

- pipelines/utils/utils.py
Filters Discord bot notifications exclusively for flows utilizing the 'basedosdados' agent
> [fix] filter prefect discord bot notification  

- pipelines/datasets/br_cvm_oferta_publica_distribuicao/tasks.py
remove dataframe = pd.Dataframe = pd.read_csv
> fix br_cvm_oferta_publica

- pipelines/datasets/br_bcb_estban/flows.py
- pipelines/datasets/br_bcb_estban/schedules.py
- pipelines/datasets/br_bcb_estban/tasks.py
Corrige erro no nome do parâmetro materialize_after_dump
> [fix] br_bcb_estban

- pipelines/datasets/br_ans_beneficiario/flows.py
- pipelines/datasets/br_ans_beneficiario/tasks.py
> [fix]: fix `br_ans_beneficiario`

- pipelines/datasets/br_ons_avaliacao_operacao/flows.py
- pipelines/datasets/br_ons_estimativa_custos/flows.py
- pipelines/datasets/br_ons_estimativa_custos/tasks.py
- pipelines/datasets/br_ons_estimativa_custos/utils.py
- `Servidor do portal de dados abertos da ONS bloqueia acesso de requisições feitas via prefect`
Ver [run](https://prefect.basedosdados.org/default/flow-run/766ad8b4-794e-45cb-9138-d115e152504a?logs)
- Requests feitas ao servidor da ONS pelo prefect retornam 403. 
- Requests de outros IPs funcionam normalmente;
> [fix] br_ons_

- pipelines/datasets/br_denatran_frota/flows.py
> br_denatran_frota

- pipelines/datasets/br_mp_pep_cargos_funcoes/constants.py
- pipelines/datasets/br_mp_pep_cargos_funcoes/flows.py
- pipelines/datasets/br_mp_pep_cargos_funcoes/tasks.py
- pipelines/datasets/br_mp_pep_cargos_funcoes/utils.py
~~Aguardando [painel.pep.planejamento.gov.br](http://painel.pep.planejamento.gov.br/QvAJAXZfc/opendoc.htm?document=painelpep.qvw&lang=en-US&host=Local&anonymous=true) voltar ao ar.~~
Close #691
> fix: br_mp_pep_cargos_funcoes

- pipelines/datasets/br_me_cnpj/flows.py
- pipelines/datasets/br_me_cnpj/tasks.py
- pipelines/datasets/br_me_cnpj/utils.py
- pipelines/utils/__init__.py
- pipelines/utils/transfer_files_to_prod/flows.py
- pipelines/utils/transfer_files_to_prod/tasks.py
closes #718 
- corrige o range dos arquivos a serem baixados
- retorna com o `rename_flow_run`
- cria o flow `transfer_files_to_prod` em `utils`
> [fix]: br_me_cnpj

- pipelines/datasets/br_cvm_oferta_publica_distribuicao/flows.py
- Desativa schedule até o conserto ser feito
> [fix]  br_cvm_oferta_publica_distribuicao.dia

- pipelines/datasets/br_inmet_bdmep/flows.py
- pipelines/datasets/br_inmet_bdmep/schedules.py
- pipelines/datasets/br_inmet_bdmep/tasks.py
- pipelines/datasets/br_inmet_bdmep/utils.py
close #726 
**v1.0**
- adiciona task que extrai a data de atualização da [página](https://portal.inmet.gov.br/dadoshistoricos/). Tive que usar o selenium, utilizando só o `requests` estava levando um 403
- troca schedule para rodar todos os dias 22pm
- adiciona lógica p/ checar a atualização e muda temporal coverage para "%Y-%m-%d"
> [feat]: add check_for_updates on `br_inmet_bdmep.microdados`

- pipelines/datasets/br_cgu_servidores_executivo_federal/flows.py
- pipelines/datasets/br_cgu_servidores_executivo_federal/schedules.py
- pipelines/datasets/br_cgu_servidores_executivo_federal/tasks.py
- pipelines/datasets/br_cgu_servidores_executivo_federal/utils.py
> [fix] `br_cgu_servidores_executivo_federal`

- pipelines/datasets/br_camara_dados_abertos/flows.py
- pipelines/datasets/br_camara_dados_abertos/schedules.py
- pipelines/utils/crawler_camara_dados_abertos/constants.py
* Adicionei a schedules e o flow de `Despesa`
* A tabela de `licitação` estava puxando a data máxima da coluna errada, logo, ajustei para a certa.
* A tabela de `evento_presenca_deputado` estava como `all_free`, coloquei como `part_pro`.
> [fix] br_camara_dados_abertos

- pipelines/datasets/br_bcb_agencia/constants.py
- pipelines/datasets/br_bcb_agencia/flows.py
- pipelines/datasets/br_bcb_agencia/schedules.py
- pipelines/datasets/br_bcb_agencia/tasks.py
- pipelines/datasets/br_bcb_agencia/utils.py
- Refatora crawler da tabela `agencia` em virtude do novo site de divulgação dos dados.
#780
> [fix] br_bcb_agencia

- pipelines/utils/execute_dbt_model/constants.py
- Altera número de max_retries da task wait_for_flow_run de 3 para 1
> [fix] wait_for_flow_run 

- pipelines/utils/dump_to_gcs/tasks.py
- Reduz limite de download de 5gb para 1gb
> [fix] download_data_to_gcs

- pipelines/datasets/br_ms_sih/flows.py
- pipelines/utils/crawler_datasus/tasks.py
- Reativa schedules das pipelines do conjunto br_ms_sih
> [fix] br_ms_sih

- pipelines/utils/crawler_datasus/tasks.py
- Remove parte não necessária da task check_files_to_parse que settava o ano/mês de download como 2024/04 no lugar da 'data máxima'.
> [fix] crawler_datasus

- pipelines/datasets/br_me_comex_stat/flows.py
- Ativa schedules das tabelas do conjunto br_me_comex
> [dados] br_me_comex

- pipelines/datasets/br_ans_beneficiario/flows.py
- pipelines/datasets/br_ans_beneficiario/tasks.py
> [fix] br_ans_beneficiarios

- pipelines/datasets/br_cgu_emendas_parlamentares/flows.py
- pipelines/datasets/br_cgu_emendas_parlamentares/schedules.py
- pipelines/utils/metadata/constants.py
- pipelines/utils/metadata/utils.py
* Consertando o `dataset_id` e `table_id`
* Alterando o `code_owners`
* Problema ao colocar uma parte pro na tabela, uma vez que o `update_django_metadata` não aceita apenas a coluna ano como `time_delta`. 
1. Adicionei o `date_column` no metadata para conseguir obter tabelas que só disponibilizam da coluna ano.
2. [Flow run SUCCESS](https://prefect.basedosdados.org/default/flow-run/bbf02dcb-79cd-44fd-8a07-eb5019a891f9?logs)
> [fix] br_cgu_emendas_parlamentares

- pipelines/datasets/mundo_transfermarkt_competicoes/flows.py
- pipelines/datasets/mundo_transfermarkt_competicoes/tasks.py
- pipelines/datasets/mundo_transfermarkt_competicoes/utils.py
*Consertar copa_brasil e adicionar check_if_data_is_outdated*
- Foi colocado uma nova task [get_data_source_max_date](https://github.com/basedosdados/pipelines/compare/staging/mundo_transfermarkt_competicoes?expand=1#diff-35db1ac75a11603fe6feb553c44454134c27fa089f98c5c8cbb9a696527769bbR34) para ser usada em conjuto com `check_if_data_is_outdated`
- Novos [Seletores](https://github.com/basedosdados/pipelines/compare/staging/mundo_transfermarkt_competicoes?expand=1#diff-42c7828382d5dc2f2db674c64c528e320b560edc787ccbedbd10fff89710867aR892) para coletar dados da pagina inicial.
> [Fix] mundo_transfermarkt_competicoes.copa_brasil

- pipelines/datasets/br_anatel_telefonia_movel/schedules.py
- pipelines/datasets/br_poder360_pesquisas/flows.py
* Consertando o semestre da telefonia movel. [Rodei em dev](https://prefect.basedosdados.org/default/flow-run/cd2c83de-25f7-4793-ba79-510488f4d918?logs)
* Desativando pipeline do poder360, ela não foi mais atualizada.
> br_anatel_telefonia_movel.microdados l br_poder360_pesquisas.microdados

- pipelines/datasets/__init__.py
- Adiciona __init__.py em br_sfb_sicar para o prefect importar o flow
> [fix] br_sfb_sicar

- pipelines/datasets/br_tse_eleicoes/flows.py
A nomeação de cada Pull Request (PR) deve seguir o seguinte padrão:
---
Atualmente o site do TSE está bloquear IP fora do Brasil. Estamos desativando a pipeline por enquanto
> [Deactivate]Desativar br_tse_eleicoes

- pipelines/datasets/br_me_cnpj/flows.py
Este PR desativa a schedule da pipeline br_me_cnpj durante a atividade de refatoração e migração do formato de partições da tabela
> [Deactivate] br_me_cnpj

- pipelines/datasets/br_anatel_banda_larga_fixa/schedules.py
- pipelines/datasets/br_anatel_telefonia_movel/schedules.py
- pipelines/utils/crawler_anatel/banda_larga_fixa/tasks.py
* Ajustando o schedules e o path para o arquivo de banda larga fixa
> [bugfix] br_anatel

- pipelines/datasets/br_ibge_inpc/flows.py
- pipelines/datasets/br_ibge_ipca/flows.py
- pipelines/datasets/br_ibge_ipca15/flows.py
- pipelines/utils/crawler_ibge_inflacao/flows.py
- Este PR resolve o problema das schedules que não são registradas **_br_ibge_inpc.mes_categoria_municipio_** & **_br_ibge_ipca15.mes_brasil_**
> [BugFix] br_ibge_

- pipelines/datasets/br_cvm_fi/tasks.py
Este PR modifica o nome da coluna cnpj que mudou na fonte original
#914
> [Bugfix] br_cvm_fi__documentos_balancete

- pipelines/datasets/br_me_cnpj/utils.py
- Este PR ajusta  o pool de conexões criado para gerenciar o download async de chunks dos arquivos do conjunto br_me_cnpj
> [Refactor] br_me_cnpj

- pipelines/datasets/cross_update/utils.py
- pipelines/utils/dump_to_gcs/tasks.py
- pipelines/utils/metadata/utils.py
- poetry.lock
- pyproject.toml
Algumas pipelines estão quebrando. Continuação de #933
https://prefect.basedosdados.org/default/flow-run/707ba233-5cb5-4dc4-ba95-6976a0a84c1f?logs
https://prefect.basedosdados.org/default/flow-run/541df51c-8c2c-4198-a237-3adb5cfd9c81?logs
https://prefect.basedosdados.org/default/flow-run/03bd99e0-881d-459d-840f-1f6984bedda0?logs
> fix backend response

- pipelines/datasets/mundo_transfermarkt_competicoes/flows.py
Desativando schedule da Pipeline brasileirao_serie_a que será descontinuada.
> [Deactivate] mundo_transfermarkt_competicoes.brasileirao_serie_a

- pipelines/utils/crawler_datasus/flows.py
- Abrindo a pipeline do Sinan para o projeto de comunicação da BD
> [BugFix] br_ms_sinan.microdados_dengue

- pipelines/datasets/br_inmet_bdmep/flows.py
Este PR reativa a pipeline do inmet
> [Reactivate] br_inmet_bdmep

- pipelines/datasets/br_rf_cafir/tasks.py
- pipelines/datasets/br_rf_cafir/utils.py
Resolve problema ascii 0 na materialização do BQ
> [Refactor] br_rf_cafir

- pipelines/datasets/br_stf_corte_aberta/utils.py
- A pipeline do STF estava pedindo o driver do Firefox, uma vez que ele foi atualizado. Essa pipeline é para consertar esse problema.
- Rodei na cloud e funcionou. Link: [🔗 ](https://prefect.basedosdados.org/default/flow-run/9cc3acb9-f198-4b3e-ba01-2831ef54fefb?logs) 
- Alterei o navegador do Firefox para o Chrome.
> [Bugfix] br_stf_corte_aberta.decisoes

- pipelines/datasets/br_cgu_emendas_parlamentares/flows.py
Inicialmente, a pipeline foi criada para processar um único arquivo dentro do ZIP, chamado `Emendas.csv`. No entanto, com a atualização recente, o download do ZIP agora contém três arquivos:  
- **`EmendasParlamentares.csv`** (equivalente ao antigo `Emendas.csv`, mas com novas colunas e informações adicionais)  
- **`EmendasParlamentares_Convenios.csv`**  
- **`EmendasParlamentares_PorFavorecido.csv`**  
As novas tabelas trazem informações relevantes e precisam ser consideradas na pipeline.
> [BugFix] br_cgu_emendas_parlamentares

- pipelines/datasets/br_me_comex_stat/schedules.py
Este PR altera o schedule atual para fazer a pipeline rodar todos os dias da semana.
> [refactor] br_me_comex_stat

- pipelines/datasets/br_stf_corte_aberta/flows.py
- pipelines/datasets/br_stf_corte_aberta/utils.py
- Está ocorrendo um erro de timeout na pipeline da stf, estou investigando para entender o motivo.
1. O que ocorreu foi o bloqueio para o IP estrangeiro, dessa forma, não está retornando nada do `driver.page_source`.
Conversando com o @Winzen, há a possível saída pelo proxy. Precisaríamos criar um proxy pela conta da BD no VAULT para ser utilizado dentro da pipeline, dessa forma, conseguimos rodar novamente a pipeline.
```python
import requests
proxies = {
"https": "scraperapi.country_code=br:SEUPROXY@proxy-server.scraperapi.com:8001"
}
head = {
"user-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"
}
url = 'https://transparencia.stf.jus.br/extensions/decisoes/decisoes.html'
response = requests.get(url, proxies=proxies, …
```
> [bugfix] br_stf_corte_aberta

- pipelines/datasets/br_cgu_beneficios_cidadao/flows.py
- pipelines/datasets/br_cgu_beneficios_cidadao/schedules.py
- pipelines/utils/crawler_cgu/flows.py
- pipelines/utils/crawler_cgu/tasks.py
- Consertando apenas o nome da tabela na função dict_for_table
> [BugFix] br_cgu_beneficios_cidadao

- pipelines/datasets/__init__.py
- pipelines/datasets/world_sofascore_competicoes_futebol/flows.py
- pipelines/datasets/world_sofascore_competicoes_futebol/schedules.py
- pipelines/utils/crawler_world_sofascore_competicoes_futebol/constants.py
- pipelines/utils/crawler_world_sofascore_competicoes_futebol/flows.py
- pipelines/utils/crawler_world_sofascore_competicoes_futebol/tasks.py
- pipelines/utils/crawler_world_sofascore_competicoes_futebol/utils.py
Esse PR adiciona pipelines para tabelas do conjunto [`world_sofascore_competicoes_futebol`][pr_sofascore] :
- uefa_champions_league - Rotina será executada diariamente
- brasileirao_serie_a -  Rotina será executada diariamente
- ### Entrar na pagina principal do campeonato para consegui todos os anos
Link de exemplo: `https://www.sofascore.com/pt/torneio/futebol/brazil/brasileirao-serie-a/325`<br>
- ### Pegar todas as partidas da temporada de um campeonato<br>
Link de exemplo: `https://www.sofascore.com/api/v1/unique-tournament/325/season/48982/team-events/total`<br>
Na verdade vamos usar outro link que exige paginação<br>
Link de exemplo: `https://www.sofascore.com/api/v1/unique-tournament/325/season/48982/events/last/0`<br>
- ### Pegar as estatisticas da partida:<br>
Link de exemplo: …
> [dados] world_sofascore_competicoes_futebol

- pipelines/datasets/br_camara_dados_abertos/flows.py
- pipelines/utils/crawler_camara_dados_abertos/constants.py
- pipelines/utils/crawler_camara_dados_abertos/flows.py
- pipelines/utils/crawler_camara_dados_abertos/tasks.py
- pipelines/utils/crawler_camara_dados_abertos/utils.py
- Identificamos a necessidade de atualizar a pipeline para incluir o processamento do ano atual e do ano anterior, considerando que os dados de anos anteriores continuam sendo atualizados. Essa alteração é essencial para garantir a consistência e a atualização contínua da base de dados.
> [BugFix] br_camara_dados_abertos

- models/test_dataset/test_dataset__test_table.sql
> Migration: test table approve (2)

- pipelines/utils/metadata/tasks.py
- Typo na task check_if_data_is_outdated retorna true para pipelines onde não há atualizações disponíveis
> [Bug] Conserta Typo na task check_if_data_is_outdated

- .github/workflows/scripts/table_approve.py
- .github/workflows/scripts/utils.py
- models/test_dataset/test_dataset__test_table.sql
Estava usando o backend da BD ao invés do prefect.
Esse PR também remove o suporte para detectar alterações em arquivos `schema.yml` e executar o test dev model e o table-approve. Volta para o formato antigo, é preciso modificar o arquivo .sql para executar o test dev model e o table approve para o modelo.
> table-approve: fix gql.transport.exceptions.TransportQueryError

- pipelines/utils/execute_dbt_model/tasks.py
Ao mesclar `dict` ele não deve ser `None`. `_vars` está como `None`.
[Flow](https://prefect.basedosdados.org/default/flow-run/3a81d91a-8b0a-42e3-b221-c17b6ae62125?logs=&logId=3d148729-c749-4ad7-8677-1d7f62f9cc76)
```
Task 'run_dbt_and_download_data_to_gcs': Exception encountered during task execution!
Traceback (most recent call last):
File "/opt/venv/lib/python3.10/site-packages/prefect/engine/task_runner.py", line 876, in get_task_run_state
value = prefect.utilities.executors.run_task_with_timeout(
File "/opt/venv/lib/python3.10/site-packages/prefect/utilities/executors.py", line 454, in run_task_with_timeout
return task.run(*args, **kwargs)  # type: ignore
File "/home/runner/work/pipelines/pipelines/pipelines/utils/execute_dbt_model/tasks.py", line 161, in …
```
> [bugfix]: execute_dbt_model run_dbt task

- CONTRIBUTING.md
Este PR coloca o guia unicado de contribuição para desenvolvimento de pipelines e subida de dados sem pipelines para validação da equipe dados. 
As principais alterações foram feitas no [PR](https://github.com/basedosdados/pipelines/pull/1012) por @aspeddro 
As principais atualizações foram:
1.  Atualização da documentação de configuração do ambiente para desenvolvimento de pipelines.
2. Inserção da seção de configuração do ambiente para densenvolvimento de modelos DBT.
3. Inserção de exemplo do processo de subida de dados (antiga wiki de primeiros passos), para códigos que não são pipelines.
4. Seção de testes com DBT
#TODO: Acho que podemos remover a parte de criação de conjuntos de dados relaciona a lógica de pastas do escritório de dados (ver linha 144)
> [Docs] revisão da nova documentação

- pipelines/datasets/br_ibge_inpc/flows.py
- pipelines/datasets/br_ibge_ipca/flows.py
- pipelines/datasets/br_ibge_ipca15/flows.py
- pipelines/datasets/br_ms_cnes/flows.py
Algumas pipelines ainda precisam de algumas alterações para se adaptar ao novo formato do repositório:
- br_ms_cnes.profissional -> [Exemplo log][log_br_ms_cnes]
Erros relacionados a utilizada na pipeline API:
- br_ibge_inpc todos os flows -> [Exemplo log][log_br_ibge_inpc]
- br_ibge_ipca todos os flows -> [Exemplo log][log_br_ibge_ipca]
- br_ibge_ipca15 todos os flows -> [Exemplo log][log_br_ibge_ipca15]
Elas estão sendo desativadas temporariamente para alterações necessárias.
[log_br_ms_cnes]: https://github.com/user-attachments/files/20243580/logs.txt
[log_br_ibge_inpc ]: https://github.com/user-attachments/files/20243754/br_ibge_inpc.txt
[log_br_ibge_ipca ]: https://github.com/user-attachments/files/20243625/br_ibge_ipca.txt
[log_br_ibge_ipca15 ]: …
> [Deactivate] Desativar pipelines que precisam fix/refatorar

- models/br_inep_sinopse_estatistica_educacao_basica/br_inep_sinopse_estatistica_educacao_basica__docente_localizacao.sql
- Ajustando as colunas de rede e localização que a @vilelaluiza identificou erros.
> [BugFix] br_inep_sinopse_estatistica_educacao_basica

- models/br_ibge_pam/br_ibge_pam__lavoura_permanente.sql
- models/br_ibge_pam/br_ibge_pam__lavoura_temporaria.sql
- Atualizando os dados da `br_ibge_pam`
> [Update] br_ibge_pam 

- pipelines/datasets/br_me_cnpj/flows.py
- pipelines/datasets/br_me_cnpj/tasks.py
- pipelines/datasets/br_me_cnpj/utils.py
- pipelines/utils/metadata/tasks.py
- Este PR altera a lógica de extração da data de divulgação das tabelas no FTP da Receita Federal. Esta data é utilizada para gerar as partições no Storage e na tabela materializada
> [BugFix] br_me_cnpj

- models/br_inep_sinopse_estatistica_educacao_basica/br_inep_sinopse_estatistica_educacao_basica__docente_deficiencia.sql
- models/br_inep_sinopse_estatistica_educacao_basica/br_inep_sinopse_estatistica_educacao_basica__docente_escolaridade.sql
- models/br_inep_sinopse_estatistica_educacao_basica/br_inep_sinopse_estatistica_educacao_basica__docente_etapa_ensino.sql
- models/br_inep_sinopse_estatistica_educacao_basica/br_inep_sinopse_estatistica_educacao_basica__docente_faixa_etaria_sexo.sql
- models/br_inep_sinopse_estatistica_educacao_basica/br_inep_sinopse_estatistica_educacao_basica__docente_localizacao.sql
- models/br_inep_sinopse_estatistica_educacao_basica/br_inep_sinopse_estatistica_educacao_basica__docente_regime_contrato.sql
- models/br_inep_sinopse_estatistica_educacao_basica/code/sinopse_2024.py
- models/br_inep_sinopse_estatistica_educacao_basica/schema.yml
Atualizando a tabela de docentes da Sinopses Estatísticas da Educação Básica para 2024
Também foi feito a correção reportado em #1098 com a tabela docente_localizacao
Close #1098
> [update]: br_inep_sinopse_estatistica_educacao_basica tabela docentes

- .github/workflows/cd.yaml
Em #1017 esse step foi removido porque demorava. Adicionando novamente como um job independente.
Ele vai ser executado depois do job `deploy-staging`. Vai ser acionado em um push no ramo main (PR mergeado).
Relacionado com #1097 e #1123
> [chore]: add script delete_archieved_flow_runs

- pipelines/datasets/br_bcb_agencia/flows.py
- pipelines/datasets/br_bcb_estban/flows.py
Este PR desativa as pipelines br_bcb_estban e br_bcb_agencia para posterior fix
> [Bugfix] br_bcb_estban & br_bcb_agencia

- pipelines/datasets/br_anatel_banda_larga_fixa/flows.py
- pipelines/datasets/br_anatel_telefonia_movel/flows.py
- Desativando as pipelines da Anatel.
- Ainda não consegui investigar o erro, mas é um erro de teste.
> [Deactivate] br_anatel

- models/br_me_comex_stat/schema.yml
- pipelines/datasets/br_me_comex_stat/flows.py
- pipelines/datasets/br_me_comex_stat/schedules.py
…ination_of_columns on br_me_comex_stat__municipio_exportacao. Also changed all flows code owner's
A nomeação de cada Pull Request (PR) deve seguir o seguinte padrão:
---
- Exemplos de título:
- **[docs] br_me_caged**
- **[Feature] br_cgu_servidores_publicos**
- Ao abrir o PR, deverá coloca-lo como draft
- Explique de maneira clara e concisa o objetivo deste PR. O que foi alterado? Qual o problema que ele resolve?
- **Motivação/Contexto:** 
- Detalhe as mudanças mais técnicas, como ajustes na pipeline, scripts ou modelo de dados utilizado.
- **Principais alterações na pipeline/scripts:** 
- **Mudanças nos dados …
> [fix] br_me_comex_stat

- uv.lock
> [chore]: upgrade `yamlfix` and `ruff`

- pipelines/utils/execute_dbt_model/tasks.py
https://github.com/basedosdados/pipelines/pull/1182#issuecomment-3307255537
> [bugfix]: `run_dbt` check if file exists

- pipelines/datasets/br_ms_cnes/flows.py
Depois do merge de #1213  podemos voltar ativar a pipeline `br_ms_cnes.profissional`
> [fix] br_ms_cnes.profissional Ativar Schedule 

- models/br_ms_sia/br_ms_sia__producao_ambulatorial.sql
- pipelines/datasets/br_ms_sia/flows.py
1. Reativa o schedule da pipeline
2. Melhora a lógica do modelo SQL para consumir menos processamento
2.1 Lógica incremental no começo do modelo para trabalhar somente com os dados que precisam ser adicionados desde o início
2.2 Join com id_municipios feito somente após is_incremental
2.3 Remoção de um select * desnecessário no final do modelo
> [Reactive/Refactor] br_ms_sia.producao_ambulatorial

- pipelines/datasets/br_me_caged/flows.py
- pipelines/datasets/br_me_caged/schedules.py
Reativa schedules dos flows das 3 tabelas do CAGED 
1. Cada flow passa a ter um schedule próprio;
2. Cada execução do flow atualiza a próxima execução com base nas datas de divulgação do caged;
> [fix] br_me_caged_schedules

- pipelines/datasets/br_rf_cafir/utils.py
> [Bugfix] br_rf_cafir.imoveis_rurais

- models/br_ibge_pam/br_ibge_pam__lavoura_permanente.sql
- models/br_ibge_pam/br_ibge_pam__lavoura_temporaria.sql
- models/br_ibge_pam/lavoura_permanente/code/api_to_json.py
- models/br_ibge_pam/lavoura_permanente/code/json_to_parquet.py
- models/br_ibge_pam/lavoura_temporaria/code/api_to_json.py
- models/br_ibge_pam/lavoura_temporaria/code/json_to_parquet.py
A nomeação de cada Pull Request (PR) deve seguir o seguinte padrão:
- Atualizando dados do IBGE PAM para 2024
> [Update] br_ibge_pam

- models/br_ibge_inpc/br_ibge_inpc__mes_brasil.sql
- models/br_ibge_inpc/br_ibge_inpc__mes_categoria_brasil.sql
- models/br_ibge_inpc/br_ibge_inpc__mes_categoria_municipio.sql
- models/br_ibge_inpc/br_ibge_inpc__mes_categoria_rm.sql
- models/br_ibge_inpc/schema.yml
- models/br_ibge_ipca/br_ibge_ipca__mes_brasil.sql
- models/br_ibge_ipca/br_ibge_ipca__mes_categoria_brasil.sql
- models/br_ibge_ipca/br_ibge_ipca__mes_categoria_municipio.sql
- models/br_ibge_ipca/br_ibge_ipca__mes_categoria_rm.sql
- models/br_ibge_ipca/schema.yml
- models/br_ibge_ipca15/br_ibge_ipca15__mes_brasil.sql
- models/br_ibge_ipca15/br_ibge_ipca15__mes_categoria_brasil.sql
- models/br_ibge_ipca15/br_ibge_ipca15__mes_categoria_municipio.sql
- models/br_ibge_ipca15/br_ibge_ipca15__mes_categoria_rm.sql
- models/br_ibge_ipca15/schema.yml
A nomeação de cada Pull Request (PR) deve seguir o seguinte padrão:
- Registrando novamente o modelo.
> Register ibge inflacao
